coventGardenStudios/coventGarden/coventGarden/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("studios.urls")),
]

coventGardenStudios/coventGarden/studios/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.conf.urls.static import static

from coventGarden import settings
from studios import views
from .forms import UserPasswordResetForm, UserPasswordSetForm


urlpatterns = [
    path('', views.placeholder, name='placeholder'),

    # Navigation
    path('', views.home, name='home'),
    path('actualites/', views.news, name='news'),
    path('studios/', views.studios, name='studios'),
    path('concert/', views.concert, name='concert'),
    path('bar/', views.bar, name='bar'),
    path('espace_pro/', views.pro_area, name='pro_area'),
    path('reservation/', views.booking, name='booking'),
    path('contact/', views.contact, name='contact'),

    # Account
    path('compte/connexion/', views.account_sign_in, name='account_sign_in'),
    path('compte/inscription/', views.account_sign_up, name='account_sign_up'),
    path('compte/deconnexion/', views.account_log_out, name='account_log_out'),

    # Profile
    path('compte/', views.profile_detail, name='profile_detail'),
    path('compte/modifier/', views.profile_update, name='profile_update'),

    # Groups
    path('compte/mes_groupes/', views.groups_detail, name='groups_detail'),
    path('compte/mes_groupes/ajouter/', views.groups_create, name='groups_create'),
    path('compte/mes_groupes/modifier/<int:group_id>/', views.groups_update, name='groups_update'),
    path('compte/mes_groupes/supprimer/<int:group_id>/', views.groups_delete, name='groups_delete'),

    # Bookings
    path('compte/mes_reservations/', views.bookings_detail, name='bookings_detail'),
    path('compte/mes_reservations/ajouter/', views.bookings_create, name='bookings_create'),

    # Planning
    path('all_events/', views.all_events, name='all_events'),
    path('add_event/', views.add_event, name='add_event'),
    path('update/', views.update, name='update'),
    path('remove/', views.remove, name='remove'),
    path('calendar/', views.calendar_view, name='calendar'),

    # Password Reset
    path('compte/mot-de-passe/oublie/',
         PasswordResetView.as_view(
             template_name='password_reset/password_reset_forgot.html',
             html_email_template_name='password_reset/password_reset_email.html',
             form_class=UserPasswordResetForm),
         name='password_reset_forgot'),
    path('compte/mot-de-passe-oublie/envoi/',
         PasswordResetDoneView.as_view(
             template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),
    path('compte/mot-de-passe-oublie/modification/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='password_reset/password_reset_confirm.html',
             form_class=UserPasswordSetForm),
         name='password_reset_confirm'),
    path('compte/mot-de-passe-oublie/confirmation/',
         PasswordResetCompleteView.as_view(
             template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),

    # Booking
    path('api/all_booking/', views.all_booking, name='all_booking'),
    path('users/', views.list_users, name='list_users'),
    path('salles/', views.list_salles, name='list_salles'),
    path('paiement-accompte/', views.accompte, name='accompte'),
    path('payment/', views.payment, name='payment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coventGardenStudios/coventGarden/studios/models.py
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

from .fields import *

# Create your models here.
class CustomUser(AbstractUser):
    """
    Default
        username
        first_name
        last_name
        email
        password
    """
    test_field = MODELS_TEST
    phone = MODEL_USER_PHONE

    def __str__(self):
        return self.username

class CustomGroup(models.Model):
    user = models.ForeignKey(
        to=CustomUser,
        on_delete=models.CASCADE,
        related_name='my_groups'
    )
    name = MODEL_NAME
    email = MODEL_EMAIL
    phone = MODEL_GROUP_PHONE
    members = MODEL_MEMBERS
    genre = MODEL_GENRE
    facebook = MODEL_FACEBOOK
    instagram = MODEL_INSTAGRAM
    twitter = MODEL_TWITTER
    biography = MODEL_BIOGRAPHY

    def __str__(self):
        return f"{self.name}"

class Event(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200, default='Untitled Event')
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    recurrence = models.CharField(max_length=200, blank=True)

class TechnicalSheet(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    pdf_file = models.FileField(upload_to='media/public', null=True)


class Salle(models.Model):
    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)

    def __str__(self):
        return f'{self.name}'

class Reservation(models.Model):
    class Status(models.TextChoices):
        RESERVED = 'Reserver'
        INPROGRESS = 'En cours'

    class Duration(models.TextChoices):
        ONE_HOUR = 1
        TWO_HOUR = 2
        THREE_HOUR = 3
        FOUR_HOUR = 4
        FIVE_HOUR = 5

    # title = models.fields.CharField(default='Item', max_length=100)
    description = models.fields.CharField(max_length=1000)
    duration = models.fields.IntegerField(choices=Duration.choices)
    date_start = models.DateTimeField(null=False)
    date_end = models.DateTimeField(null=False)
    # hour_begin = models.TimeField(null=False)
    price = models.fields.IntegerField(validators=[MinValueValidator(1)])
    status = models.fields.CharField(choices=Status.choices, max_length=20)
    salle = models.ForeignKey(Salle, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

coventGardenStudios/coventGarden/studios/forms.py
from django.contrib.auth.forms import (UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm)
from .models import CustomUser, CustomGroup, Event
from .fields import *

# Register your forms here
"""
CustomUser (Tutorial)
"""
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

"""
Account
    - Sign In
    - Sign Up
"""
class SignInForm(forms.Form):
    username = FORM_USERNAME
    password = FORM_PASSWORD

class SignUpForm(forms.Form):
    username = FORM_USERNAME
    email = FORM_EMAIL
    last_name = FORM_LAST_NAME
    first_name = FORM_FIRST_NAME
    password = FORM_PASSWORD
    confirm_password = FORM_PASSWORD_CONFIRM

"""
Profile
    - User Update
    - Confirm Password
"""
class UserUpdateForm(forms.Form):
    username = FORM_USERNAME
    email = FORM_EMAIL
    last_name = FORM_LAST_NAME
    first_name = FORM_FIRST_NAME

class ConfirmPasswordForm(forms.Form):
    current_password = FORM_PASSWORD_CURRENT
    confirm_password = FORM_PASSWORD_CONFIRM

"""
Password Reset
    - Reset
    - Set
"""
class UserPasswordResetForm(PasswordResetForm):
    # Replaced PasswordResetForm fields with custom fields (See docs)
    email = FORM_EMAIL

class UserPasswordSetForm(SetPasswordForm):
    # Replaced SetPasswordForm fields with custom fields (See docs)
    new_password1 = FORM_PASSWORD
    new_password2 = FORM_PASSWORD_CONFIRM

"""
CustomGroup
    - Create
"""
class GroupCreateForm(forms.ModelForm):
    # User will be added manually in views.py
    class Meta:
        model = CustomGroup
        fields = '__all__'
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

"""
Planning
    - Event
"""
class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'start_time', 'end_time', 'recurrence']

"""
Concert
    - Technical sheet
"""
class TechnicalSheetForm(forms.Form):
    pdf_file = forms.FileField(label='Déposer la Fiche Technique')

"""
Booking
"""
class ReservationForm(forms.Form):
    name = forms.CharField(max_length=LENGTH_NAME, label="Nom de l'utilisateur")
    email = forms.EmailField(label="Email de utilisateur")

    salle = forms.CharField(max_length=20, label="Salle réservée")
    # description = models.fields.CharField(max_length=1000)
    duration = forms.IntegerField(label="Durée de la séance en (H)")
    date_start = forms.DateTimeField(label="Date de début reservation")
    date_end = forms.DateTimeField(label="Date de fin reservation")
    # hour_begin = forms.TimeField( label="Heure de début de la réservation")
    price = forms.IntegerField(label="Montant payé en £")

    # status = models.fields.CharField(choices=Status.choices, max_length=20)

    def __init__(self, *args):
        super(ReservationForm, self).__init__(*args)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class TestForm(forms.Form):
    test = FORM_GROUP_NAME

coventGardenStudios/coventGarden/studios/templates/bar.html
{% extends 'base/base.html' %}
{% load static %}



<!-- Insert page title -->
{% block title %}

<title>Bar</title>

{% endblock %}



<!-- Insert page main header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Insert page content -->
{% block content %}

<!-- Container -->
<div class="container">

	<!-- Breadcrumb -->
	<ol class="breadcrumb">
    	<li><a href="{% url 'home' %}">Accueil</a></li>
    	<li class="active">Bar</li>
	</ol> <!-- /Breadcrumb -->

	<!-- Main content -->
	<div class="row">

		<!-- Article -->
		<article class="col-sm-12 maincontent">

			<!-- Header -->
			<header class="page-header">
				<h1 class="page-title">Bar</h1>
		  	</header>

			<!-- Content 1  -->
			<div class="row">
				<div class="col-sm-6">
					<a class="navbar-brand"><img src="{% static 'studios/images/De_Sutter.png' %}" text-center></a>
				</div>

				<div class="col-sm-6">
					<p><img src="{% static 'studios/images/mac.jpg' %}" alt="presentation_studios"></p>
				</div>
			</div>

			<!-- Content 2 -->
			<p>Depuis de nombres années, le Covent Garden Studios fait confiance à la <a href="http://www.brasseriedesutter.com/" target="_blank" rel="noopener">Brasserie De Sutter</a> pour leur fournir une bière artisanale de qualité.</p>
			<p>La Brasserie De Sutter est fondée par deux frères, Antoine et Frédéric, passionnés par la bière et par sa fabrication. En 2008, ils se lancent dans des tests de création de recettes et suite à l’obtention de leurs diplômes en agronomie ainsi qu’en brasserie, les premières bières voient le jour. Rapidement confortés par la qualité de leurs produits, les brasseurs installent une unité de production artisanale de 800 litres.</p>  
			<p>En janvier 2012, c’est le grand saut vers une fabrication maîtrisée et de plus grosse capacité grâce au déménagement de la Brasserie De Sutter à Gisors dans des locaux plus grands avec du matériel de brassage neuf et performant.</p>
			
			<!-- Content 3 -->
			<div class="swiper mySwiper">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-ambree-rousse-dement-bree.png' %}" alt="Dément'brée">
					</div>
					
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-blanche-givree_1.png' %}" alt="Givrée">
					</div>
					
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-blonde-brin-de-folie.png' %}" alt="Brin de Folie">
					</div>
					
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-sombre-folle-brune.png' %}" alt="Folle Furieuse">
					</div>
					
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-fruits-rouges-folle-des-bo.png' %}" alt="Folle des bois">
					</div>
					
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-ipa-crazy-indian-pale-ale.png' %}" alt="Crazy - IPA">
					</div>
					
					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-zinzin-quadruple-fermentat.png' %}" alt="Zin Zin">
					</div>

					<div class="swiper-slide">
						<img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-ictis.jpg' %}" alt="Ictis - Bio">
					</div>
				</div>
			</div>
	
		</article> <!-- /Article -->
	
	</div> <!-- /Main content -->

</div> <!-- /Container -->

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

	<!-- Slider CSS -->
	<link rel="stylesheet" href="{% static 'studios/css/slider.css' %}"/>

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />

	<!-- Demo styles -->
	<style>
		.swiper {
		width: 100%;
		padding-top: 50px;
		padding-bottom: 50px;
		}

		.swiper-slide {
		background-position: center;
		background-size: cover;
		width: 240px;
		height: 240px;
		}

		.swiper-slide img {
		display: block;
		width: 100%;
		}
	</style>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

	<!-- Swiper JS -->
	<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>

	<!-- Initialize Swiper -->
	<script>
		var swiper = new Swiper(".mySwiper", {
		  effect: "coverflow",
		  grabCursor: true,
		  centeredSlides: true,
		  slidesPerView: "auto",
		  coverflowEffect: {
			rotate: 35,
			stretch: 0,
			depth: 40,
			modifier: 1,
			slideShadows: false,
		  },
		  pagination: {
			el: ".swiper-pagination",
		  },
		  initialSlide: 2, // Affiche la 3e image (index 2) par défaut
		});
	</script>

{% endblock %}

coventGardenStudios/coventGarden/studios/templates/booking.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}

<title>Réservation</title>

{% endblock %}


{% block style %}
    <link rel="stylesheet" href="{% static 'studios/css/booking.css' %}">
{% endblock %}


{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}


{% block content %}

<div class="container">

    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">Accueil</a></li>
        <li class="active">Réservation</li>
    </ol>
    <div class="row">

		{% if messages %}
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

		<div class="col-xs-12 maincontent">
			<header class="page-header">
				<h1 class="page-title">Réservation</h1>
			</header>
			
			<div id="calendar" class="col-md-12">
			
			</div>
		</div>
		
	</div>
</div> <!-- /container -->

<div class="modal" id="confirmation-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Information de la réservation</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form id="confirm-form" action="{% url 'accompte' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="salle">Studios choisi :</label>
                        <input id="salleName" name="salleName" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="start_date">Date et heure de début :</label>
                        <input type="datetime" name="date_start" id="startDate" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Date et heure de fin :</label>
                        <input type="datetime" name="date_end" id="endDate" class="form-control" required>
                    </div>
                   
                    <input type="hidden" name="salle_id" id="idSalle">
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Confirmer</button>
                    <button type="button" id="cancel-btn" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src='https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.8/index.global.min.js'></script>
<script src="{% static 'studios/js/booking.js' %}"></script>
{% endblock %}

coventGardenStudios/coventGarden/studios/templates/concert.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Insert title -->
{% block title %}

<title>Concert</title>

{% endblock %}



<!-- Insert main header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Insert content -->
{% block content %}

<!-- Container -->
<div class="container">

	<!-- Breadcrumb -->
	<ol class="breadcrumb">
        <li><a href="{% url 'home' %}">Accueil</a></li>
        <li class="active">Concert</li>
	</ol> <!-- /Breadcrumb -->

	<!-- Main content -->
	<div class="row">

		<!-- Article -->
		<article class="col-sm-12 maincontent">

			<!-- Header -->
			<header class="page-header">
				<h1 class="page-title">Concert</h1>
		  	</header>

            <!-- Content 1 -->
			<div class="row">
				<div id="calendar"></div>
			</div>
	
		</article> <!-- /Article -->
	
	</div> <!-- /Main content -->

</div> <!-- /Container -->

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

	<link rel="stylesheet" href="{% static 'studios/css/concert.css' %}"/>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

	<script src="{% static 'studios/js/concert.js' %}"></script>

	<!-- External JavaScript dependencies -->
	<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.8/index.global.min.js'></script>
	<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.8/index.global.min.js'></script>

{% endblock %}

coventGardenStudios/coventGarden/studios/templates/contact.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Insert title -->
{% block title %}

<title>Contact</title>

{% endblock %}



<!-- Insert main header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Insert content -->
{% block content %}

<!-- Container -->
<div class="container">

	<!-- Breadcrumb -->
	<ol class="breadcrumb">
        <li><a href="{% url 'home' %}">Accueil</a></li>
        <li class="active">Contact</li>
	</ol> <!-- /Breadcrumb -->

	<!-- Main content -->
	<div class="row">

		<!-- Article -->
		<article class="col-sm-12 maincontent">

			<!-- Header -->
			<header class="page-header">
				<h1 class="page-title">Contact</h1>
		  	</header>

            <!-- Content 1 -->
			<div class="stud">
				<!-- Button(s) -->
				<div class="button">
					<a class="btn btn-action btn-lg" href="{% url 'booking' %}" role="button">Réserver un studio</a>
				</div>

				<!-- Content -->
				<div class="row">

					<!-- Left -->
					<div class="col-sm-6">
						<h2>Horaires :</h2><br>
						<table class="table-center">
							<tbody>
								<tr><td>Lundi - Vendredi</td><td>16h00 -  </td><td>00h00</td></tr>
								<tr><td>Samedi *</td><td>10h00 - </td><td>18h00</td></tr>
								<tr><td>Dimanche</td><td>13h00 - </td><td>21h00</td></tr>
							</tbody>
						</table>
						
						<!-- Add link concert-->
						<br><p>*Ouverture jusqu'à minuit les soirs de concerts. <a href="{% url 'placeholder' %}">Placeholder!</a></p>
					</div>

					<!-- Right -->
					<div class="col-sm-6">
						<h2>Studios de répétition</h2><br>
						E-Mail : <a href="mailto:contact@coventgarden.fr">contact@coventgarden.fr</a><br>
						Tel : <a href="tel:0130365291">01 30 36 52 91</a>
					</div>
				</div>
			</div>

			<!-- Content 2 -->
			<div class="stud">
				<div class="row">
					<!-- Left -->
					<div class="col-sm-6">
						<h2>Adresse :</h2><br>
						<p><a href="https://goo.gl/maps/xwy7vnXwuFTFXfJA8" target="_blank">
							1 Rue du Bouvreuil,<br>
							Parc d'activité de la Danne<br>
							95610, Eragny-sur-Oise
						</a></p>
					</div>

					<!-- Right -->
					<div class="col-sm-6">
						<h2>Programmation</h2><br>
						E-Mail : <a href="progra@coventgarden.fr">progra@coventgarden.fr</a>
					</div>
				</div>
			</div>

			<!-- Content 3 -->
			<div class="studss">
				<div class="row">
					<!-- Left -->
					<div class="col-sm-6">
						<h2>Accès :</h2><br>
						<div class="access">
							<ul>
								<li>Voiture : A proximité de la N184 et A15</li>
								<li>RER A, arrêt Cergy-Préfecture ou Neuville Université</li>
								<li>Transilien ligne J, arrêt Eragny-Neuville</li>
								<li>Bus : ligne 49 Cergy Préfecture RER / Neuville Université RER, arrêt écluse</li>
							</ul>
						</div>
					</div>

					<!-- Right -->
					<div class="col-sm-6">
						<h2>Autres questions</h2><br>
						E-Mail : <a href="progra@coventgarden.fr">progra@coventgarden.fr</a><br>
						Tel : <a href="tel:0130365291">01 30 36 52 91</a>
					</div>
				</div>
			</div>

			<!-- Content 4 (Google Maps) -->
			<div class="row">
				<div class="col-sm-6">
					<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d125603.48773383588!2d2.176306205946799!3d48.95927429137867!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6f5531a0bd495%3A0xc89a34ac7b94d4e9!2sCovent%20Garden%20Studios!5e0!3m2!1sfr!2sfr!4v1687936492555!5m2!1sfr!2sfr" width=100% height="350" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
				</div>
			</div>

		</article> <!-- /Article -->
	
	</div> <!-- /Main content -->

</div> <!-- /Container -->

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

<link rel="stylesheet" href="{% static 'studios/css/contact.css' %}"/>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

{% endblock %}

coventGardenStudios/coventGarden/studios/templates/payment.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Insert title -->
{% block title %}

<title>Paiement accompte</title>

{% endblock %}



<!-- Insert main header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Insert content -->
{% block content %}

<!-- Container -->
<div class="container">

	<!-- Breadcrumb -->
	<ol class="breadcrumb">
        <li><a href="{% url 'home' %}">Accueil</a></li>
        <li>Réservation</li>
		<li class="active">Paiement accompte</li>
	</ol> <!-- /Breadcrumb -->

	<!-- Main content -->
	<div class="row">

		<!-- Article -->
		<article class="col-sm-12 maincontent">

			<!-- Header -->
			<header class="page-header">
				<h1 class="page-title">Paiement accompte</h1>
			</header>

            <!-- Content 1: Form -->
			<form  action="{% url 'payment' %}" method="POST">
				{% csrf_token %}
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<!-- Title / Text -->
							<h3 class="thin text-center">Paiement accompte</h3>
							<p class="text-center text-muted">Nous demandons le paiement d’un acompte pour la réservation d’une aventure. Nous ajusterons le tarif le jour de l’événement en fonction du nombre de personnes présentes.</p>

							<hr>

							<!-- Include form(s) here -->
							{% include "base/base_form.html" %}
                            <input type="hidden" name="salle_id" value="{{ salle.id }}">
                            <input type="hidden" name="user_id" value="{{ user.id }}">

							<hr>

							<!-- Button(s) -->
							<div class="row">
								<!-- Confirm -->
								<div class="col-lg-12 text-right">
									<button class="btn btn-action" type="submit">Confirmer</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
	
		</article> <!-- /Article -->
	
	</div> <!-- /Main content -->

</div> <!-- /Container -->

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

	<link rel="stylesheet" href="{% static 'studios/css/booking.css' %}">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

	<script src="{% static 'studios/js/payment.js' %}"></script>

	<script>
		$('#id_name').val("{{user.username}}");
		$('#id_email').val("{{user.email}}");
		$('#id_salle').val("{{salle.name}}");
		$('#id_duration').val("duration");
		$('#id_date_start').val("{{ start_date }}");
		$('#id_date_end').val("{{ end_date }}");
	</script>

{% endblock %}